export const FETCH_DECKS_STARTED = 'FETCH_DECKS_STARTED';
export const FETCH_DECKS_SUCCESS = 'FETCH_DECKS_SUCCESS';
export const FETCH_DECKS_FAILURE = 'FETCH_DECKS_FAILURE';

export const GET_DECK = 'GET_DECK';

export const ADD_DECK_STARTED = 'ADD_DECK_STARTED';
export const ADD_DECK_SUCCESS = 'ADD_DECK_SUCCESS';
export const ADD_DECK_FAILURE = 'ADD_DECK_FAILURE';

export const REMOVE_DECK_STARTED = 'REMOVE_DECK_STARTED';
export const REMOVE_DECK_SUCCESS = 'REMOVE_DECK_SUCCESS';
export const REMOVE_DECK_FAILURE = 'REMOVE_DECK_FAILURE';
