export const FETCH_PROD_STARTED = 'FETCH_PROD_STARTED';
export const FETCH_PROD_SUCCESS = 'FETCH_PROD_SUCCESS';
export const FETCH_PROD_FAILURE = 'FETCH_PROD_FAILURE';

export const ADD_PROD_STARTED = 'ADD_PROD_STARTED';
export const ADD_PROD_SUCCESS = 'ADD_PROD_SUCCESS';
export const ADD_PROD_FAILURE = 'ADD_PROD_FAILURE';

export const REMOVE_PROD_STARTED = 'REMOVE_PROD_STARTED';
export const REMOVE_PROD_SUCCESS = 'REMOVE_PROD_SUCCESS';
export const REMOVE_PROD_FAILURE = 'REMOVE_PROD_FAILURE';
